name: OS Quality Control

on:
  # Trigger the robot on every push to master or staging
  push:
    branches: [ "master","main", "staging" ]
  # Also trigger when someone opens a Pull Request to master
  pull_request:
    branches: [ "master" ]

jobs:
  phpcs-lint:
    name: PHP Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS
        run: composer lint